apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e4u08gli2-go
  janus-idp.io/tekton: e4u08gli2-go
  backstage.io/kubernetes-id: e4u08gli2-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e4u08gli2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
