apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e4u08gli2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:af387bd79fda1b77377219c2f3eea141dd2b2584@sha256:8edffd863c8fd3199c129414d48a0d4fe29bedd79bb7e0a866fe8ce09b989911
          name: container-image
